#!/bin/bash

util=${SUDO_USER:-$USER}
# Check if Script is Run as user 
if [[ $EUID -ne 0 ]]; then

  tar -xvzf config/config_mx_linux.tar.gz
  
  # Synchronise le contenu en toute sécurité
  rsync -a --delete .config/ "$HOME/.config/"

  sudo ./script/install_begin

  ./script/bookmark_install 

  rm /home/$util/.vbox*

  sudo mx-snapshot -c -z xz
  
  echo -ne "
-------------------------------------------------------------------------
                    Wait until the reboot ...
-------------------------------------------------------------------------
"&& sleep 10

  sudo reboot
  else
  echo "You must be a non-root user to run this script, please run ./install" 2>&1

  exit 1
fi

