#!/bin/bash

apt update -y && apt upgrade -y 

apt install -y $(grep -vE '^#|^$' txt/apt.txt | xargs)

apt remove -y $(grep -vE '^#|^$' txt/remove.txt | xargs)

apt update -y

apt autoremove -y

apt install -f 