#!/bin/bash
set -e

echo "📦 Mise à jour des dépôts..."
apt update -y && apt upgrade -y

echo "🟢 Installation des paquets utiles..."
grep -vE '^#|^$' txt/apt.txt | xargs -r apt install -y

echo "🔴 Suppression des paquets inutiles..."
grep -vE '^#|^$' txt/remove.txt | xargs -r apt remove -y

echo "🧹 Nettoyage..."
apt update -y
apt autoremove -y
apt install -f
