#!/bin/bash

util=${SUDO_USER:-$USER}

systemctl mask suspend.target hibernate.target

# Copier /etc/environment
rsync -a --chown=root:root config/environment /etc/environment

#config autologin 
crudini --set /etc/lightdm/lightdm.conf SeatDefaults autologin-user "$util"
crudini --set /etc/lightdm/lightdm.conf SeatDefaults autologin-user-timeout 0
crudini --set /etc/lightdm/lightdm.conf SeatDefaults autologin-session xfce

# Sudoers (chmod spécial)
rsync -a --chown=root:root config/sudoers /etc/sudoers
chmod 440 /etc/sudoers

# Polkit rules
rsync -a --chown=root:root config/disable-passwords.rules /etc/polkit-1/rules.d/

# mx-snapshot exclude
rsync -a --chown=root:root config/mx-snapshot-exclude.list /etc/

#Cleaning packages 
apt autoclean
apt clean
apt autoremove -y 
apt purge ~c -y 



