#!/bin/bash

util=${SUDO_USER:-$USER}

FILE="/etc/lightdm/lightdm.conf"

systemctl mask suspend.target hibernate.target

#modif /etc/environment 
rm /etc/environment 

chown root:root config/environment
chmod 644 config/environment
mv config/environment /etc/environment

#config autologin 
sudo crudini --set /etc/lightdm/lightdm.conf SeatDefaults autologin-user "$util"
sudo crudini --set /etc/lightdm/lightdm.conf SeatDefaults autologin-user-timeout 0
sudo crudini --set /etc/lightdm/lightdm.conf SeatDefaults autologin-session xfce

#modif /etc/sudoers
rm /etc/sudoers

chown root:root config/sudoers
chmod 440 config/sudoers
mv config/sudoers /etc/sudoers

#Add policyKit (polkit) rules, allowing to use gtk root application without password
chown root:root config/disable-passwords.rules
chmod 644 config/disable-passwords.rules
mv config/disable-passwords.rules /etc/polkit-1/rules.d/disable-passwords.rules

rm /home/$util/.vbox*
mkdir -p /home/snapshot/{work,snapshots}

#Cleaning packages 
apt autoclean
apt clean
apt autoremove -y 
apt purge ~c -y 



